baseURL = 'https://nohv.site/'
languageCode = 'en-us'
title = 'Nohv'
theme = 'PaperMod'
enableRobotsTXT = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  [params.homeInfoParams]
    Title = "Welcome"
  
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Geun-Oh"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/hyeonggeun-oh-760a5b240/"
  env = "production"

[[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 10
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 10
[[menu.main]]
  identifier = "database"
  name = "Database"
  url = "/database/"
  weight = 10
[[menu.main]]
  identifier = "network"
  name = "Network"
  url = "/network/"
  weight = 10
[[menu.main]]
  identifier = "os"
  name = "OS"
  url = "/os/"
  weight = 10
[[menu.main]]
  identifier = "cs"
  name = "CS"
  url = "/cs/"
  weight = 10
[[menu.main]]
  identifier = "devops"
  name = "DevOps"
  url = "/devops/"
  weight = 10

