baseURL = 'https://geun-oh.github.io'
languageCode = 'en-us'
title = 'Nohv'
theme = 'PaperMod'
enableRobotsTXT = true

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  [params.homeInfoParams]
    Title = "Welcome"
    Content = """
    Software Engineer
    Love tools that streamline processes(like neovim & nix..)
    Delving deeper into Operating System, Network and Database
    Does not locked in specific programming language, use proper language in each context
    Friendly using Go, Typescript and Zig

    At home, post general purpose programming stuffs like Distributed System, System Programming,,, or everything I'm interested in.
    """

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Geun-Oh"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/hyeonggeun-oh-760a5b240/"
  [[params.socialIcons]]
    name = "cv"
    url = "https://drive.google.com/file/d/1feRPHsii2lctkqZEvZ5VCEkZ7z3ejU3-/view?usp=sharing"

  env = "production"

[[menu.main]]
  identifier = "database"
  name = "Database"
  url = "/database/"
  weight = 10
[[menu.main]]
  identifier = "network"
  name = "Network"
  url = "/network/"
  weight = 10
[[menu.main]]
  identifier = "os"
  name = "OS"
  url = "/os/"
  weight = 10

