baseURL = 'https://geun-oh.github.io'
languageCode = 'en-us'
title = 'Nohv'
theme = 'PaperMod'
enableRobotsTXT = true

[services]
  [services.googleAnalytics]
    id = "G-MDH2SL5MH9"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  mainSections = ["implementations-engineerings", "knowledge_base-reviews", "thoughts"]
  defaultTheme = "light"
  disableThemeToggle = true
  
  [params.comments]
  enable = true

  [params.home]
  orderBy = "publishDate"
  orderDirection = "desc"

  [params.homeInfoParams]
    Title = "Hyeonggeun Oh"
    Content = """
    Software Engineer
    
    - Love tools that streamline processes(like neovim & nix..)
    - Delving deeper into Operating System, Network and Database
    - Does not locked in specific programming language,
      use proper language in each context
    - Friendly using Go, Typescript and Zig

    At home, post general purpose programming stuffs like Distributed System,
    System Programming,,, or everything I'm interested in.
    """

  [params.giscus]
  repo = "Geun-Oh/geun-oh.github.io"
  repoID = "R_kgDOMiZJ6g"
  category = "General"
  categoryID = "DIC_kwDOMiZJ6s4CnzGI"
  mapping = "og:title"
  dataStrict = "1"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "light"
  lang = "en"
  loading = "lazy"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/Geun-Oh"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/hyeonggeun-oh-760a5b240/"
  [[params.socialIcons]]
    name = "medium"
    url = "https://medium.com/@geunoh"
  [[params.socialIcons]]
    name = "cv"
    url = "https://drive.google.com/file/d/1qwHOTQBxNqdS-RQHdzXeJzqAHjvaU7XY/view?usp=drive_link"

  env = "production"

[[menu.main]]
  identifier = "Implementations & Engineerings"
  name = "Impl & Engineerings"
  url = "/implementations-engineerings/"
  weight = 10
[[menu.main]]
  identifier = "Knowledge Bases & reviews"
  name = "KB & Reviews"
  url = "/knowledge_base-reviews/"
  weight = 10
[[menu.main]]
  identifier = "Thoughts"
  name = "Thoughts"
  url = "/thoughts/"
  weight = 10

